services:
  - type: web
    name: emotion-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    region: oregon
    plan: free
    runtime: python
    pythonVersion: 3.10
